import db from "@/lib/prisma";

// ---------------------------------------------------------------------------
// Types — mirrors the JSON structure generated by the LLM script
// ---------------------------------------------------------------------------

export interface MasterProfileData {
  bio: string; // 投资人个人履历亮点
  fundOverview: string; // 基金公司历史与业绩概述
}

export interface MasterProfileResult {
  profile: MasterProfileData;
  source: string;
  version: number;
  generatedAt: Date;
}

// ---------------------------------------------------------------------------
// Query
// ---------------------------------------------------------------------------

export async function getMasterProfile(
  tribeId: string,
): Promise<MasterProfileResult | null> {
  try {
    const row = await db.masterProfile.findFirst({
      where: { entity: { tribeId } },
      select: {
        profile: true,
        source: true,
        version: true,
        generatedAt: true,
      },
    });

    if (!row) return null;

    return {
      profile: row.profile as unknown as MasterProfileData,
      source: row.source,
      version: row.version,
      generatedAt: row.generatedAt,
    };
  } catch {
    return null;
  }
}
