-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" TEXT NOT NULL DEFAULT 'user';

-- CreateTable
CREATE TABLE "CreditLedger" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "delta" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "period" TEXT,
    "refId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CreditLedger_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "CreditLedger_userId_period_createdAt_idx" ON "CreditLedger"("userId", "period", "createdAt");

-- AddForeignKey
ALTER TABLE "CreditLedger" ADD CONSTRAINT "CreditLedger_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateIndex (partial unique index — Prisma schema DSL cannot declare this;
-- only constrains "grant" reasons so repeated spend_agent inserts in the same
-- period are unaffected. Applied by hand via $executeRawUnsafe alongside the
-- statements above, not generated by `prisma migrate diff`.)
CREATE UNIQUE INDEX "CreditLedger_grant_period_key"
  ON "CreditLedger"("userId", "reason", "period")
  WHERE "reason" IN ('grant_free', 'grant_plan');
